### PR TITLE
[WIP] Fix for 0.7 

### PR DESCRIPTION
**Pull request by rejuvyesh**
Has some large deps like `JuMP` that need updates first.

### CODE REVIEW

**Comment by ajkeith** [comment]
From what I can tell, JuMP will take some time to update to 1.0 but the master version is already working or mostly working. If there's a way to change the dependency to the master version of JuMP, that might speed up the conversion process, but there are probably some big trade-offs to doing that.

**Comment by ajkeith** [comment]
@rejuvyesh thanks for the help on this earlier. Where did the uuid in your branch come from? I made the updates to the main files for 1.0 from the master and everything tests fine locally, but I'm stuck on fixing the travis.yaml file for the CI testing. I merged my changes into master already because I was thinking it might be a branch issue. Appreciate any advice you might have on fixing the travis file.

**Comment by rejuvyesh** [comment]
See https://github.com/JuliaPOMDP/POMCPOW.jl/blob/master/.travis.yml for an example?

**Comment by ajkeith** [comment]
Thanks for taking a look. It turns out the problem was that my `manifest.toml` and `project.toml` files were mismatched (I got some help on discourse [here](https://discourse.julialang.org/t/travis-ci-for-an-unregistered-package/19447). I'm cleaning up the readme now, but then everything should be good. Should I submit a PR to the POMDPs page to move the solver out of the "awaiting update" box?

**Comment by rejuvyesh** [comment]
Once your tests pass, definitely! I would recommend tagging a release and I'll add it to the POMDP registry.

**Comment by zsunberg** [comment]
@ajkeith awesome! Yeah, when it works on 1.0, please do submit a PR to move it to the other section in the POMDPs README, and tag a version and have @rejuvyesh add it to the registry

**Comment by ajkeith** [comment]
Okay sounds good, thanks for the help!

**Pull request closed without merging**
